version: '{{ cookiecutter.__docker_compose_version }}'

services:
  requirements:
    build:
      context: docker/requirements
    volumes:
      - ./requirements:/requirements
    env_file:
      - .env-test
  test:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
      args:
        REQUIREMENTS: test
        DJANGO_SETTINGS_MODULE: '{{ cookiecutter.django_project_name }}.settings_test'
        PYTHONPATH: /app/src:/app/tests
    entrypoint: /app/tests/entrypoint.sh
    env_file:
      - .env-test
    environment:
      DJANGO_DEBUG:
      DJANGO_DEBUG_SQL:
      DJANGO_DEBUG_SQL_LIMIT:
      PYTHONHUNTER:
      PYTHONHUNTERCONFIG:
      SERVER_NAME: localhost
      DJANGO_SECRET_KEY: test123
      SENTRY_DSN: ''
    stop_signal: SIGINT
    depends_on:
      - pg
    volumes:
      - ./:/app
      - ./.home:/home/app
  pg:
    build:
      context: docker/postgres
    env_file:
      - .env-test
    command: [
      'postgres',
      '-c', 'log_statement=all',
      '-c', 'log_duration=true',
      '-c', 'log_disconnections=true',
      '-c', 'log_connections=true',
      '-c', 'log_lock_waits=true',
      '-c', 'log_min_error_statement=WARNING',
      '-c', 'log_min_duration_statement=1s',
    ]
