# An alternative dev configuration with the more simple devserver (easier to debug but you lose dev-prod parity)
services:
  pg:
    ports:
      - '5432:5432'
  web:
    environment:
      DJANGO_DB_MIGRATE: x
    privileged: true
    ports:
      - '80:8000'
    command: [
      'pysu', 'app', '--',
      'django-admin', 'runserver', '--insecure', '0.0.0.0:8000'
    ]
    stop_signal: SIGINT
    tty: true
