services:
  requirements:
    build:
      context: docker/requirements
    volumes:
      - ./requirements:/requirements
    env_file:
      - .env-test

  test:
    extends:
      service: python
      file: docker-compose.common.yml
    build:
      args:
        REQUIREMENTS: test
        DJANGO_SETTINGS_MODULE: '{{ cookiecutter.django_project_name }}.settings_test'
        PYTHONPATH: /app/src:/app/tests
    entrypoint: /app/tests/entrypoint.sh
    env_file:
      - .env-test
    environment:
      DJANGO_DEBUG:
      DJANGO_DEBUG_SQL:
      DJANGO_DEBUG_SQL_LIMIT:
      PYTHONHUNTER:
      PYTHONHUNTERCONFIG:
      SERVER_NAME: localhost
      DJANGO_SECRET_KEY: test123
      SENTRY_DSN: ''
    stop_signal: SIGINT
    depends_on:
      - pg
    volumes:
      - ./:/app
      - ./.home:/var/app

  pg:
    extends:
      service: pg
      file: docker-compose.common.yml
    env_file:
      - .env-test
